"""add_persistence_fields

Revision ID: 5f90cb866138
Revises: 20260909_1300
Create Date: 2026-09-25 23:46:02.193375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f90cb866138'
down_revision = '20260909_1300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing rows
    op.add_column('study_plans', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('study_plans', sa.Column('progress_percentage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('current_plan_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_session_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_session_id')
    op.drop_column('users', 'current_plan_id')
    op.drop_column('study_plans', 'progress_percentage')
    op.drop_column('study_plans', 'is_active')
    # ### end Alembic commands ###
