"""add_quiz_attempt_status

Revision ID: a5825f5d2af5
Revises: a1b2c3d4e5f6
Create Date: 2026-10-01 07:39:56.470549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5825f5d2af5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('status', sa.String(), nullable=True, server_default='not_started'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'status')
    # ### end Alembic commands ###
